axiethernet: Fix bsp generation error in a custom design
In custom design having multiple ethernet instances and dma is not
connected to one of ethernet instance, driver tcl error out with:

ERROR: [Common 17-55] 'get_property' expects at least one object.
Resolution: If [get_<value>] was used to populate the object, check
to make sure this command returns at least one valid object.
ERROR: [Hsi 55-1545] Problem running tcl command ::sw_axiethernet_v5_10
::generate : ERROR: [Common 17-55] 'get_property' expects at least one
object.
Resolution: If [get_<value>] was used to populate the object, check to
make sure this command returns at least one valid object.

    while executing
"get_property  CONFIG.C_BASEADDR $target_periph"
    ("foreach" body line 62)
    invoked from within
<snip>
"::sw_axiethernet_v5_10::generate egbeth_eth_egbeth"

The reason for this failure is in xdefine_axi_target_params function
validentry variable is not re-initialized for each eth instance and
as a result even though dma is not connected to second eth instance
we end up calling get_property on a NULL object. To fix initialize
validentry for each axiethernet instance and also add a check for
get_connected_intf return value.

Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@xilinx.com>

Acked-for-series: Harini Katakam <harini.katakam@xilinx.com>