freertos10_xilinx: Fix compilation errors with freertos os
XScuGic_ConfigTable is declared as extern in xscugic.h to fix
misra-c violations. This fix generates compilation error for
versal, zynqmp and zynq platforms when built with freertos
as XScuGic_ConfigTable is declared as extern const in freertos.
Remove const to fix the compilation errors.

portZynqUltrascale.c:133:29: error: conflicting types for
'XScuGic_ConfigTable'.

Signed-off-by: Shravya Kumbham <shravya.kumbham@xilinx.com>
Acked-by:  Mubin Usman Sayyed <mubin.usman.sayyed@xilinx.com>