xxvethernet : Fix gcc warnings
Removed unused variables and included header file for usleep.
Fixes below gcc warnings:

xxxvethernet.c:684:2: warning: implicit declaration of function
 'usleep' [-Wimplicit-function-declaration]
xxxvethernet.c:673:6: warning: unused variable 'i' [-Wunused-variable]
xxxvethernet.c:707:6: warning: unused variable 'i' [-Wunused-variable]

Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@xilinx.com>

Acked-for-series: Harini Katakam <harini.katakam@xilinx.com>