BSP: Add workaround to handle_stdout_parameter proc
get_mem_ranges is showing unexpected behavior for
some of the versal HW designs, it is returning same
instance of SBSA UART multible times. Due to that
PLM BSP creation is failing with below error,

ERROR: [Hsi 55-1545] Problem running tcl command ::sw_standalone_v7_2
::generate : expected integer but got "0xFF000000 0xFF000000
0xFF000000 0xFF000000 0xFF00"
while executing
"format "0x%08llX" $value

Updated handle_stdout_parameter to add workaround for
stated issue.

Signed-off-by: Mubin Usman Sayyed <mubin.usman.sayyed@xilinx.com>

Acked-by: Siva Durga Prasad Paladugu <siva.durga.paladugu@xilinx.com