axicdma: To fix the compilation error
As xpseudo_asm.h includes xreg_cortexa9.h, xpseudo_asm_gcc.h
and xreg_cortexr5.h files which are required for ARM and cortex-R5,
removing xreg_cortexa9.h under __MICROBLAZE__ and replacing
xpseudo_asm_gcc.h with xpseudo_asm.h preprocessor to fix the
xaxicdma_example_hybrid_intr.c compilation error.
../src/xaxicdma_example_hybrid_intr.c:92:10:
fatal error: xreg_cortexa9.h: No such file or directory
              ^~~~~~~~~~~~~~~~~
compilation terminated.
src/subdir.mk:21: recipe for target
'src/xaxicdma_example_hybrid_intr.o' failed
make: *** [src/xaxicdma_example_hybrid_intr.o] Error 1.

Signed-off-by: Shravya Kumbham <shravya.kumbham@xilinx.com>

Acked-for-series: Radhey Shyam Pandey <radhey.shyam.pandey@xilinx.com>

Acked-for-series: Radhey Shyam Pandey <radhey.shyam.pandey@xilinx.com>