xdmapcie: Fix the yaml syntax issue
commit 9f91d0147aba (xdmapcie: Adds support for SDT flow)
introduced a bug due to inconsist spaces in the compatible list,
After this commit while try to set the repo getting below error.
ERROR:
TypeError: 'NoneType' object is not subscriptable.

This commit fixes this issue.

Signed-off-by: Appana Durga Kedareswara rao <appana.durga.kedareswara.rao@amd.com>
Acked-by: Onkar Harsh <onkar.harsh@amd.com>