xiltimer: Fix compilation failures related to MB V default timer
When xiltimer is configured to use default MB V timer as sleep timer,
it fails to compile due to following errors,

error: conflicting types for 'Xil_GetRISCVFrequency'; have
'u32(void)' {aka 'long unsigned int(void)'}
  128 | u32 Xil_GetRISCVFrequency(void)

/xmicroblaze_riscv_config.h:16:24: error: initializer element
is not constant
   16 | #define XGet_CpuFreq() XMicroblaze_RISCV_ConfigTable.CpuFreq

Signed-off-by: Mubin Sayyed <mubin.sayyed@amd.com>

Acked-for-series: Siva Durga Prasad Paladugu <siva.durga.prasad.paladugu@amd.com>