scugic: Call get_port_width with namespace
Existing scugic.tcl has one instance of get_port_width
which is being called without namespace, it is resulting
into below errors with 2019.2 builds,

ERROR: [Hsi 55-1545] Problem running tcl command
::sw_scugic_v4_1::generate : invalid command name "get_port_width"

Added namespace to get_port_width call to fix above errors.

Signed-off-by: Mubin Usman Sayyed <mubin.usman.sayyed@xilinx.com>