BSP: arm: common: Fix linker issues in c++ apps build with SDT flow
getentropy.c is not being picked up by build infra in SDT flow.
It is causing linker error for C++ applications

aarch64-xilinx-elf-ld.real: aarch64-xilinx-elf/usr/lib64/libc.a(libc_a-getentropyr.o):
in function `_getentropy_r': (.text+0x24): undefined reference to `_getentropy'

Signed-off-by: Mubin Sayyed <mubin.sayyed@amd.com>

Acked-for-series: Siva Durga Prasad Paladugu <siva.durga.prasad.paladugu@amd.com>