spips: Update spips selftest example to fix compilation issue
When the hard spips and PL(soft) spi IP are in the same design (xsa
file) and someone creates a peripheraltest for this, they end up in
a build failure.
PeripheralTest application pulls in self test examples for both the
drivers and both the drivers use the same name "Spi" to define the
instance name. It results in a link error as:

/proj/xbuilds/SWIP/2022.1_0330_2143/installs/lin64/Vitis/2022.1/gnu/aarch64/lin/aarch64-none/x86_64-oesdk-linux/usr/bin/aarch64-xilinx-elf/aarch64-xilinx-elf-ld.real: ./src/xspips_selftest_example.o:/proj/dsv_xhd/skemidi/regression_2020/IPS/som/new_test/peri/Debug/../src/xspips_selftest_example.c:54: multiple definition of `Spi'; ./src/xspi_selftest_example.o:/proj/dsv_xhd/skemidi/regression_2020/IPS/som/new_test/peri/Debug/../src/xspi_selftest_example.c:65: first defined here

The solution is not to use the same name "Spi" to define the instances
in the drivers.

Signed-off-by: Anirudha Sarangi <anirudha.sarangi@xilinx.com>

Acked-for-series: Amit Kumar Mahapatra <amit.kumar-mahapatra@xilinx.com>