xilpm: server_versal: Fix compilation error in xpm_board.c
Compilation error introduced because of following commit:
- 0ebe3dae93a95b2bd8e52559a61820ecea36cb2a
  (xilpm: server_versal: Create file for board specific functions)

xpm_board.c:58:37: error: 'XPm_Core' {aka 'struct XPm_Core'} has no member named 'RegAddress'
  Status = XPlmi_UtilPollForMask((Pmc->RegAddress[0] +

Fix this error by using PMC GLOBAL base address from XPm_Pmc structure
instead of XPm_Core.

Signed-off-by: Rajan Vaja <rajan.vaja@xilinx.com>