lib: bsp: standalone: Fix xil_nested_interrupts_example compilation error
Remove unnecessary "XScuGic_SetPriTrigTypeByDistAddr" API calling
to fix the compilation error as below:
error: 'INTC_DIST_BASEADDR' undeclared (first use in this function).

It fixes commit 0de3e09499507070504dcb3ccf493b20fdab122b
("lib: standalone: ported examples for SDT flow")

Signed-off-by: M Lakshmaiah <lakshmaiah.m@amd.com>

Acked-for-series: Mubin Sayyed <mubin.sayyed@amd.com>