drivers: Fix compilation errors and warnings
- Resolved invalid function pointer conversion from void (*)(void*) to void*
  by explicitly casting function pointers in XSetupInterruptSystem().
- Suppressed unused parameter warnings in TickHandler() and PWMHandler()
  by using (void)CallBackRef to explicitly mark them as unused.
- Ensured correct function signatures and parameter usage for clean compilation.

Fixed the following errors and warnings:
error: invalid conversion from 'void (*)(void*)' to 'void*' [-fpermissive]
error: invalid conversion from 'u32 (*)(XTtcPs*)' {aka 'unsigned int (*)(XTtcPs*)'}
       to 'void*' [-fpermissive]
warning: unused parameter 'CallBackRef' [-Wunused-parameter]
warning: unused parameter 'BaseAddr' [-Wunused-parameter]
warning: 'GicConfig' defined but not used [-Wunused-variable]

Signed-off-by: M Lakshmaiah <lakshmaiah.m@amd.com>

Acked-for-series: Mubin Sayyed <mubin.sayyed@amd.com>