xxvethernet: Fix bsp generation error in a custom design
In custom design having multiple xxv instances and mcdma is not
connected to one of xxv instance, driver tcl error out with:
ERROR: [Common 17-161] Invalid option value '' specified for 'object'.
ERROR: [Hsi 55-1545] Problem running tcl command ::sw_xxvethernet_v1_1]
:generate : ERROR: [Common 17-161] Invalid option value '' specified
for 'object'. get_property  CONFIG.C_BASEADDR $target_periph"

The reason for this failure is in xdefine_axi_target_params function
validentry variable is not re-initialized for each xxv instance and
as a result even though mcdma is not connected to second xxv instance
we end up calling get_property on a NULL object. To fix initialize
validentry for each xxv instance.

Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@xilinx.com>

Acked-for-series: Harini Katakam <harini.katakam@xilinx.com>