xilplmi: Create dummy IPI APIs if there is no IPI instance is defined.
XilSEM uses IPI interface from Xilplmi library. If there is no IPI
instance, PLM build with pre build Libxilsem.a failing due to
undefined reference to IPI APIs.
To fix this error, create dummy APIs if there is no IPI instance
present in design.
Corrected IPI instance dependency check in SDT flow.

Signed-off-by: Gayathri <gayathri.m@amd.com>

Acked-for-series: Rama devi Veggalam <rama.devi.veggalam@amd.com>