Revert "dp14: Add support for YUV420 color format"
This reverts commit e13ed4363d62299a4dd693ebbcbe56170b34158e.

Revert this commit as it is giving compilation error as
"xdp_spm.c:1176:18: error: 'MsaConfig' undeclared" and needs more
thorough testing

Signed-off-by: Rajesh Gugulothu <gugulothu.rajesh@xilinx.com>

Acked-for-series: Vishal Sagar <vishal.sagar@xilinx.com>