lwip: Fix axiethernet applications build failure
Incase interrupt pin is connected to multiple interrupt sources derive
intc_periph_type value programmatically, instead of assuming the order
of get_connected_intr_cntrl API output i.e {psu_rcpu_gic psu_acpu_gic}
It fixes the below app build failure.

ERROR: axi_ethernet (axi_eth_0) interrupt port connected to more than
one IP. lwIP requires that the interrupt line be connected only to
the interrupt controller

Signed-off-by: Radhey Shyam Pandey <radhey.shyam.pandey@xilinx.com>

Acked-for-series: Appana Durga Kedareswara rao <appana.durga.rao@xilinx.com>